### ISSUE TITLE
DB2 SSL use Windows Truststore

### ISSUE THREAD

**Issue by dvag-david-dylong** [IBM/db2forzosdeveloperextension-about#101]
hello,

how can i configure the Db2 For z/OS Developer Exentsion Plugin to use the Windows truststore on SSL Connection to Db2 ?

**Comment by katsoohoo** [comment]
Hi @dvag-david-dylong,

Since you've mentioned Windows TrustStore, I assume you'd like to make an SSL connection to Db2 using server authentication.

On your local machine, you'll need to import the CA certificate and the Db2 server certificate into the Windows TrustStore. 

In the extension, create a Db2 connection with **Port** as the SSL port. In the **Optional** tab, define the following JDBC properties:
```json
"sslConnection": "true",
"sslTrustStoreLocation": "NUL",
"sslTrustStoreType": "Windows-ROOT"
```
![Screen Shot 2023-04-24 at 16 39 46](https://user-images.githubusercontent.com/5027555/234138420-f61d2e74-c927-4917-af15-7d3b2c693914.png)

With this, you should be able to establish an SSL connection to a Db2 server using the certificates stored in Windows TrustStore.

**Comment by dvag-david-dylong** [comment]
oo thanks god!! it works. I would never ever found out by myself, that i have to set sslTrustStoreLocation to NUL.
