### ISSUE TITLE
Altering stored procedures with different input variables/lengths

### ISSUE THREAD

**Issue by nlopresti** [IBM/db2forzosdeveloperextension-about#36]
I'm not sure if this is more of a process change on our end or something that should be addressed in the deploy logic. Upon making an adjustment to a stored procedure (increasing the length of an input variable), I received the error code below **-20314 THE PARAMETER LIST (OR AN OPTION) DOES NOT MATCH THE PARAMETER LIST (OR OPTION) FOR ALL OTHER VERSIONS OF ROUTINE routine-name**

This is in fact what I was trying to do... change the parameter size. I changed versions and anything I could think of to get this to work. The only thing that did work, was dropping the stored procedure manually first and then running the create. What I noticed is that the sql statements above the create do not get executed during a deploy and it's the logic behind the scenes that converts it into an alter (as we discussed earlier this week). Therefore in order for this to work, we drop it manually first. Is this the correct process? Or should it be something that can be accomplished programmatically behind the scenes?

**Comment by realkendrickren** [comment]
@nlopresti Hi Nick, that is because Db2 doesn't allow to alter the existing version if the signature is changed. 

For this case, in the deployment options, you could choose "Drop duplicates" option instead of the default "Alter duplicates" option, see the attached screenshot, the extension would then drop the existing version for you before creating the new version, so you don't need to manually do that. 

But, there is one restriction that the extension doesn't support today, the situation is when you have other stored procedures that invoke the one to be deployed and  you chose "Drop duplicates", the extension does not automatically drop those stored procedures because it may cause big impact, so you will get an SQL error from the DROP attempt under this situation.
![image](https://user-images.githubusercontent.com/26660024/110700908-803a3600-81be-11eb-8478-2d022e65990a.png)

**Comment by nlopresti** [comment]
@realkendrickren Thanks for the reply, the only reason that I wrote this issue is because I've exhausted all of those options. I tried to turn on the drop duplicates setting, and the issue still exists. I can walk you through it again. It's almost as if it doesn't take in the parameter for drop. It's still attempting to alter. See my screenshots below...I've tried my window's version as well, both do not work.

![image](https://user-images.githubusercontent.com/44413010/110800043-cdafb500-8249-11eb-8a32-f6318e66eeae.png)
![image](https://user-images.githubusercontent.com/44413010/110800085-d86a4a00-8249-11eb-9116-0e5528d5c5a6.png)

**Comment by realkendrickren** [comment]
@nlopresti thanks a lot for the further information. I understood the issue you got into now, we'll evaluate the solution for this one and keep you posted.

**Comment by nlopresti** [comment]
Thanks @realkendrickren if you need to jump on a call to see it live please let me know...much appreciated.

**Comment by realkendrickren** [comment]
@nlopresti Just let you know, a temp workaround at the moment is to take out "VERSION V1" option from the stored procedure DDL, and choose "Drop duplicates" to proceed, if you like to try out. V1 is the default in Db2 if you don't specify. In this case, the stored procedure signature is changed, you won't get other versions anyway under the same schema (of course, if you want to specify a different version for this signature, the workaround will not get you there, you would have to put VERSION back and do another round of deployment).

**Comment by realkendrickren** [comment]
@nlopresti we just published a new version v1.1.2, which handles the signature change of the stored procedure during the deployment when you choose "Drop duplicates". Please upgrade and give a try.
