### ISSUE TITLE
SP Debugger server can not load JCC Driver

### ISSUE THREAD

**Issue by turnerm92** [IBM/db2forzosdeveloperextension-about#39]
When trying to debug a stored proc the following error occurs:

_'The debugger server could not be started. Error code -9910. The JCC driver could not be loaded.'_

The plugin has the driver file configured - 'Db2sqlservice Dependencies' points to the driver/license file, and executing SQL is working fine. 
There doesn't appear top be an equivalent option for the debugger, and the debugger doesn't appear to use the Db2sqlservice setting.

Thanks

**Comment by realkendrickren** [comment]
@turnerm92 thanks for reporting the issue. 

Can you check which authentication method is being used for your connection when you launch debugger? If it is "password" method, do you check "save password"?
 The issue usually happens when the "password" method is chosen without checking "save the password". 
 
This is being enhanced in the upcoming sponsor user code drop.

**Comment by realkendrickren** [comment]
@turnerm92 we just published v1.2.0, which addresses this issue officially along with many other enhancements. Please upgrade and give a try. Thanks.
